@echo off
echo Restarting frontend with fresh environment variables...
cd frontend
echo Killing any existing node processes...
taskkill /F /IM node.exe 2>nul
timeout /t 2 /nobreak >nul
echo Starting frontend server...
npm start
